version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16
    environment:
      repo_token: b3X2uxgM7Xzlmc1tRBlMX1LWspnPWehBV
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd node-mongo-tutorial && npm install 
      - run:
          name: Install npm dev dependencies
          command: cd node-mongo-tutorial && npm install mocha c8 chai-http chai
      - run:
          name: Run Unit Tests
          command: cd node-mongo-tutorial && npm test
      - run:
          name: Upload coverage to Coveralls
          command: cd node-mongo-tutorial && npx coveralls < coverage/lcov.info
workflows:
  build_tests:
    jobs:
      - run_tests