version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16
    working_directory: ~/Server
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command:  npm install 
      - run:
          name: Install npm dev dependencies
          command:  npm install mocha c8 chai-http chai
      - run:
          name: Run Unit Tests
          command:  npm test
workflows:
  build_tests:
    jobs:
      - run_tests