version: 2.1
jobs: 
  run_tests:
    docker: 
      - image: circleci/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd node-mongo-tutorial && npm install 
      - run:
          name: Install npm dev dependencies
          command: cd node-mongo-tutorial && npm install mocha c8 chai-http chai
      - run:
          name: Run Unit Tests
          command: cd node-mongo-tutorial && npm test
workflows:
  build_tests:
    jobs:
      - run_tests